### ISSUE TITLE
#Work Plan#Mark-to-Market

### ISSUE THREAD

**Issue by ClaireWangGoForIt** [alitiffany/DefaultRisk#3]
- [x] Wednesday:Greeks; 
- [x] Thursday: PnL & Attribution: Main problem is how to get data from yesterday; 
- [x] Friday Morning: Futures; Afternoon: Summary; 
- [x] Next week: think about some enhancement.

**Comment by ClaireWangGoForIt** [comment]
- [x] digital的公式添进去；  
- [x] 用一个月的行情跑个时间序列出来（要做这种时间序列的话，就意味着有两种情况需要考虑，一种是时间段的开始，它只有dayone_pnl，一种不是时间段的开始，它有前一个交易日的信息）。目的是用统计的方法做定价。所以需要每天的PnL的数据，还需要最后那天的累计PnL的数据。

**Comment by ClaireWangGoForIt** [comment]
遗留问题：  
- [ ] ic 与ih的行情只能取出来一部分，2015-04-16之前的数据取不出来

**Comment by ClaireWangGoForIt** [comment]
New Assignment:把对冲时间调为1分钟。  
- [x] 把future换成1分钟线的数据;  
- [x] 按照现行的规则，把1分钟的数据处理一遍，这意味着后面的代码要过一遍，看有什么需要改的;  
- [x] 对冲条件改为。。。。就是那张纸上的任务，一个一个的做：注意，我觉得可以在遍历程序的过程中一个一个点的做，把那三个点都给做了。

**Comment by ClaireWangGoForIt** [comment]
跟师兄确认下：  
- [x] future与underly的时间不一致，future是早上9点15就开盘，下午3点15分收盘。但是多出来的这半个小时不用进行对冲（调仓）对吧？  
- [x] theta的计算是以分钟为单位了可以么？  
- [x] 是dollardelta为-5万的时候才需要进行对冲对吧？正向的不管。话说，这个五万的上限对于100万的本金来说，不太容易触碰到呢。。。比如说，9月1日开始的期权，根本不会触碰到这个线，离得还挺远。。它最大是第一下的-5000多，第二大的是-1000多。。。  
  这个要注意，改成1万，正向的也需要调整
- [x] 算thetaattribution的时候，应该时间乘数是（-n）对吧？因为是时间减少了嘛。。之前是正n。。。另外，这个是n对吧？因为有可能上次对冲与这次对冲之间相隔比较多的分钟。。  
  你再想想，就是正的  
- [x] 在对冲的时间上，即使是一天的开头，如果没有触碰到那个五万的线，也仍然不用对冲是吧？

**Comment by ClaireWangGoForIt** [comment]
需要改进的地方：   
- [x] 197行开始的那两个循环，还是得想办法变成lapply之类的apply啊。。。

**Comment by ClaireWangGoForIt** [comment]
注意：i的循环是因为手动跑了0了就写的1开始，还是要调回0的哈

**Comment by ClaireWangGoForIt** [comment]
plan from 20160407 noon：  
- [x] 循环的效率需要提高：先看谢益辉和alyssa frazee的两篇文章，总结下能够做出改进的方法；再去搜搜看有没有别的文章，看看。ddl：2pm；  
- [x] 把delta的限制改成正负一万;  
- [x] 频率改成3分钟线;  
- [x] 先把每周只选周三的结果跑出来（程序修改ddl：4pm），今天晚上再跑全部的数据，明天可以看结果。

**Comment by ClaireWangGoForIt** [comment]
- rowSums，colSums, rowMeans, colMeans (in base), rowSds, colSds, rowVars, colVars, rowttests, rowFtests (in genefilter), colMedians, rowMedians (in matrixStats).好用  
- 向量化：可以去dplyr或者data.table中看有没有向量化的函数；或者看程序中的循环代码是需要什么样的功能，有没有这样功能的函数  
- 矩阵可以直接和向量相乘  
- apply函数系列其实还是在做循环，并没有本质上的差别。  
- 目前来说我觉得有点困难的地方在于，这需要的是个dependent iteration。

**Comment by ClaireWangGoForIt** [comment]
plan at 20160411 1003:  
- [x] 跟师兄对结果  
- [x] 把对冲成本加进去考虑:万分之0.26_张数_点数*300  
- [x] 再跑一次的时候把attribution那里换成百分比形式的  
- [x] 计算一下平均对冲的次数  
- [x] 做一下put的结果，也对比下按天和按三分钟对冲的结果差别
- [ ] 给自己安装git&github

**Comment by ClaireWangGoForIt** [comment]
plan at 20160412 0923:  
- [x] 把call和put之前的结果汇总成一张表，对比着看一下；  
  -把call和put的阀值进行筛选，通过循环的方式选择最优的阀值设定：  
- [x] strike需要取下列数值：0.9,0.95,1,1.05,1.1  
  为了避免循环跑死，就先用1吧。。。。
- [x] 循环时的最小单位变化是整十：  
  这个根据循环的范围来算吧，就跑个十次差不多了。。。
- [x] 变化的范围自己测一下，就是看从哪里是全部都会对冲了，哪里是全部都不对冲了，就一个上限一个下限了  
- [x] 循环的最优条件是mean(sumPnL+commission)的绝对值最小  
  这个在最后得到那张表之后再筛选一下就行了。  
- [x] 输出应该是输出这样的表：期权类别，对冲频率，strike，首日的pv，对冲的阀值，平均对冲的次数，相加的绝对值大小。

**Comment by ClaireWangGoForIt** [comment]
需要考虑的地方：   
- [x] 期货可以开小数的张数  
  这个就先这么着吧，因为整数小数的这个问题要在组合层面进行考虑。  
- [x] 现在这种直接使用均值的方法（pnl和对冲天数的计算都是使用的均值），让人觉得有点担心，因为在样本数据中，波动还是挺大的，那么就不能保证在接下来开的一个开始日期的期权能重演均值的表现。。。so。。。要用别的统计的方法吗？  
  重新使用的方法是用etf来进行对冲

**Comment by ClaireWangGoForIt** [comment]
需要改进的部分： 
- [x] c9600那里有问题，只储存了11月16号之后的结果，所以会小很多。。。所以要改，其实跑的结果都出了，只是汇总部分的程序要调下看看  
- [ ] 取日行情要改成在天软中完成，不能总是用那个excel啊。。。。

**Comment by ClaireWangGoForIt** [comment]
问题：   
- [ ] 既然可以使用etf来进行对冲，为啥现在实际不用呢？
