### ISSUE TITLE
# Work Plan # 商品期货材料

### ISSUE THREAD

**Issue by ClaireWangGoForIt** [alitiffany/DefaultRisk#4]
目标：参照场外期权的文档，丰富商品衍生品的文档。这是需要自己考虑商品衍生品有什么风险特点的。主要是丰富风控部分的内容，需要在场外期权的基础上加加减减，比如，场外期权的某些特点商品衍生品没有，那么就需要删掉，还有些是商品衍生品独有的特点，就需要加上（例如，商品衍生品容易受到自然和政策等因素的影响）。  
- [x] 市场风险：可以使用delta等指标；  
- [x] 流动性风险：可以添加一个现金流预测的想法（比如，在有两个期限上不完全匹配的期权，需要一个给付的钱去支付另一个期权，那么如果第一个没有给付的话第二个就支付不了了）；可以说持仓太大，砸在手中的风险；  
- [x] 信用风险：可以说赖账的情况；可以使用风控部的授信模型；  
- [x] 注意：有些操作是只有场外期权才有而商品期货没有的，所以不能原封不动的抄上去；要用修订模式进行操作；要弄出导航来。  
- [x] 加进去一些回测的东西：  
- 写在风控的前面  
- 期货的种类与所在的交易所是一一对应的  
- 可以按照策略分类，也可以按照所在的交易所或者种类什么的分类  
- 注意：报风控批的东西，一来要让人觉得这个东西可以赚钱，二来要告诉它风险可控。

**Comment by ClaireWangGoForIt** [comment]
Random Ideas:  
- 每个风险的介绍都可以按照这样的模式：风险的定义；风险的来源分类；改进措施。
